# Generated by Django 4.0.2 on 2022-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_instock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instock',
        ),
    ]
