# Generated by Django 4.0.2 on 2022-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0008_remove_item_instock_num_remove_item_outstock_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstock',
            name='requester',
            field=models.CharField(default='', max_length=50, verbose_name='Requester'),
            preserve_default=False,
        ),
    ]
