# Generated by Django 4.0.2 on 2022-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0009_alter_outstock_requester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('model', models.CharField(choices=[('Group', 'Group'), ('Item', 'Item'), ('Instock', 'Instock'), ('Outstock', 'Outstock')], max_length=50, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Search Suggestion',
                'verbose_name_plural': 'Search Suggestions',
            },
        ),
    ]
