# Generated by Django 4.0.2 on 2022-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0010_searchsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsuggestion',
            name='display_name',
            field=models.CharField(default='', max_length=50, verbose_name='Field Display Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchsuggestion',
            name='seperator',
            field=models.CharField(default='=', max_length=20, verbose_name='Seperator'),
        ),
        migrations.AlterField(
            model_name='searchsuggestion',
            name='model',
            field=models.CharField(choices=[('Group', 'Group'), ('Item', 'Item'), ('Instock', 'Instock'), ('Outstock', 'Outstock')], max_length=10, verbose_name='Model'),
        ),
    ]
