# Generated by Django 4.0.2 on 2022-06-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0012_searchsuggestion_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsuggestion',
            name='is_number',
            field=models.BooleanField(default=False, verbose_name='Is Value of Type Number'),
            preserve_default=False,
        ),
    ]
