# Generated by Django 4.0.2 on 2022-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0013_searchsuggestion_is_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstock',
            name='instock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.instock', verbose_name='Instock'),
        ),
    ]
