# Generated by Django 4.0.6 on 2022-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0014_outstock_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='instock',
            name='quantity_left',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Quantity of Items Left in Stock'),
        ),
    ]
