# Generated by Django 4.0.6 on 2022-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0018_remove_instock_quantity_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=50, verbose_name='Min Price'),
        ),
    ]
