# Generated by Django 4.0.6 on 2022-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0019_alter_item_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PO ID'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier'),
        ),
    ]
