# Generated by Django 4.0.6 on 2022-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0021_remove_outstock_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Group Description'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='purchase_order_id',
            field=models.CharField(max_length=50, null=True, verbose_name='PO ID'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='supplier',
            field=models.CharField(max_length=50, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Item Description'),
        ),
    ]
