# Generated by Django 4.0.6 on 2022-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0023_alter_item_max_price_alter_item_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstock',
            name='customer',
            field=models.CharField(max_length=200, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='requester',
            field=models.CharField(max_length=200, verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='stock_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Stock ID'),
        ),
    ]
