# Generated by Django 3.1 on 2021-01-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('description', models.CharField(max_length=50, verbose_name='Group Description?')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('description', models.CharField(max_length=50, verbose_name='Item Description')),
                ('size', models.CharField(max_length=50, verbose_name='Item Size')),
                ('brand', models.CharField(max_length=50, verbose_name='Item Brand')),
                ('unit', models.CharField(max_length=50, verbose_name='Item Unit?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.group', verbose_name='Group Belonged To')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Ordered?')),
                ('invoice_id', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('purchase_order_number', models.IntegerField(verbose_name='PO Number')),
                ('pc_job', models.IntegerField(verbose_name='PC Job Number')),
                ('customer', models.CharField(max_length=50, verbose_name='Customer')),
                ('supplier', models.CharField(max_length=50, verbose_name='Supplier')),
                ('quantity', models.IntegerField(verbose_name='Quantity of Item Stocked')),
                ('is_instock', models.BooleanField(verbose_name='Item is Instock')),
                ('is_metalstock', models.BooleanField(verbose_name='Item is Metal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.item', verbose_name='Item Stocked')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
