# Generated by Django 3.1 on 2021-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_auto_20210117_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='customer',
        ),
        migrations.AlterField(
            model_name='stock',
            name='pc_job',
            field=models.CharField(max_length=50, verbose_name='PC Job Number'),
        ),
    ]
