# Generated by Django 3.1 on 2021-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_auto_20210130_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Item Brand'),
        ),
    ]
