# Generated by Django 3.1 on 2021-01-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_auto_20210130_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Group Description?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Item Name'),
        ),
    ]
