# Generated by Django 3.1 on 2021-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20210130_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='Item Unit?'),
        ),
    ]
