# Generated by Django 3.1 on 2021-01-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_auto_20210130_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase_order_number',
            field=models.IntegerField(null=True, verbose_name='PO Number'),
        ),
    ]
