# Generated by Django 3.1 on 2021-01-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_auto_20210130_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pc_job',
            field=models.CharField(max_length=50, null=True, verbose_name='PC Job Number'),
        ),
    ]
