# Generated by Django 3.1 on 2021-01-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0009_auto_20210130_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price per Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_order_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Purchase Order Number'),
        ),
    ]
