# Generated by Django 3.1 on 2021-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0011_auto_20210208_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Price per Item'),
        ),
    ]
