# Generated by Django 3.1 on 2021-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0012_auto_20210208_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pc_job',
            field=models.CharField(max_length=50, null=True, verbose_name='PC Job'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_order_number',
            field=models.CharField(max_length=50, null=True, verbose_name='PO Number'),
        ),
    ]
