"""Initial migration.

Revision ID: 02b48a18c1e8
Revises: 
Create Date: 2023-09-02 11:09:29.709830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b48a18c1e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('instock_number', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('outstock_number', sa.Integer(), nullable=True))
    op.drop_column('item', 'outstock')
    op.drop_column('item', 'instock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('instock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('outstock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('item', 'outstock_number')
    op.drop_column('item', 'instock_number')
    # ### end Alembic commands ###
