# Generated by Django 4.0.2 on 2022-05-15 11:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Group Description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Item Code')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Item Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Item Description')),
                ('item_type', models.CharField(choices=[('BAR', 'Bar'), ('SHEET', 'Sheet'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Type of material')),
                ('brand', models.CharField(max_length=50, null=True, verbose_name='Item Brand')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='Item Unit')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Weight KG')),
                ('number_instock', models.IntegerField(default=0, verbose_name='Number Instock')),
                ('number_outstock', models.IntegerField(default=0, verbose_name='Number Outstock')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Max Price')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Sum Price')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Min Price')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Outstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('job_id', models.CharField(max_length=50, null=True, verbose_name='Job ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Quantity of Item Stocked')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Size'), null=True, size=2)),
                ('customer', models.CharField(max_length=50, null=True, verbose_name='Customer')),
                ('stock_id', models.CharField(max_length=50, null=True, verbose_name='Stock ID')),
                ('requester', models.CharField(max_length=50, null=True, verbose_name='Requester')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='Department')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.item', verbose_name='Item Stocked')),
            ],
            options={
                'verbose_name': 'Outstock',
                'verbose_name_plural': 'Outstocks',
            },
        ),
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('job_id', models.CharField(max_length=50, null=True, verbose_name='Job ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Quantity of Item Stocked')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Size'), null=True, size=2)),
                ('invoice_id', models.CharField(max_length=50, null=True, verbose_name='Invoice ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Price per Item')),
                ('purchase_order_id', models.CharField(max_length=50, null=True, verbose_name='PO ID')),
                ('supplier', models.CharField(max_length=50, null=True, verbose_name='Supplier')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.item', verbose_name='Item Stocked')),
            ],
            options={
                'verbose_name': 'Instock',
                'verbose_name_plural': 'Instocks',
            },
        ),
    ]
