# Generated by Django 4.0.6 on 2026-05-09 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Job ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Job Name')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('name', models.CharField(max_length=50, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('description', models.CharField(max_length=200, verbose_name='Group Description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Item SKU')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Item Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Item Description')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='Item Unit')),
                ('instock_number', models.IntegerField(default=0, verbose_name='Instock Number')),
                ('outstock_number', models.IntegerField(default=0, verbose_name='Outstock Number')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Max Price')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Sum Price')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Min Price')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Quantity of Items Left Instock')),
                ('notes', models.CharField(max_length=1000, null=True, verbose_name='Notes')),
                ('min_quanity', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Minimum Quantity')),
                ('max_quanity', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Maximum Quantity')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.brand', verbose_name='Brand')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Outstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
                ('store_type', models.CharField(choices=[('metal', 'Metal'), ('accessory', 'Accessory'), ('machine', 'Machine'), ('service', 'Service')], default='metal', max_length=20, verbose_name='Store Type')),
                ('stock_id', models.CharField(max_length=200, null=True, verbose_name='Stock ID')),
                ('requester', models.CharField(max_length=200, verbose_name='Requester')),
                ('department', models.CharField(max_length=200, null=True, verbose_name='Department')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.customer', verbose_name='Customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.item', verbose_name='Item Stocked')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Outstock',
                'verbose_name_plural': 'Outstocks',
            },
        ),
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
                ('store_type', models.CharField(choices=[('metal', 'Metal'), ('accessory', 'Accessory'), ('machine', 'Machine'), ('service', 'Service')], default='metal', max_length=20, verbose_name='Store Type')),
                ('invoice_id', models.CharField(default='UNDEFINED', max_length=50, verbose_name='Invoice ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('purchase_order_id', models.CharField(max_length=50, null=True, verbose_name='PO ID')),
                ('supplier', models.CharField(max_length=50, null=True, verbose_name='Supplier')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.item', verbose_name='Item Stocked')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Instock',
                'verbose_name_plural': 'Instocks',
            },
        ),
    ]
