# Generated by Django 4.0.6 on 2026-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instock',
            name='job',
        ),
        migrations.AddField(
            model_name='instock',
            name='job',
            field=models.ManyToManyField(null=True, to='stockmanagement.job', verbose_name='Job'),
        ),
        migrations.RemoveField(
            model_name='outstock',
            name='job',
        ),
        migrations.AddField(
            model_name='outstock',
            name='job',
            field=models.ManyToManyField(null=True, to='stockmanagement.job', verbose_name='Job'),
        ),
    ]
