# Generated by Django 6.0.3 on 2026-03-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='job',
            field=models.CharField(max_length=200, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='job',
            field=models.CharField(max_length=200, null=True, verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.customer', verbose_name='Customer'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
