# Generated by Django 4.0.6 on 2026-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_remove_instock_job_instock_job_remove_outstock_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='job',
            field=models.ManyToManyField(to='stockmanagement.job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='job',
            field=models.ManyToManyField(to='stockmanagement.job', verbose_name='Job'),
        ),
    ]
