# Generated by Django 6.0.3 on 2026-03-20 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_alter_instock_job_alter_outstock_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
    ]
