# Generated by Django 4.0.2 on 2022-05-21 13:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_delete_instock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(null=True, verbose_name='Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('job_id', models.CharField(max_length=50, null=True, verbose_name='Job ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Quantity of Item Stocked')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Size'), null=True, size=2)),
                ('invoice_id', models.CharField(max_length=50, null=True, verbose_name='Invoice ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Price per Item')),
                ('purchase_order_id', models.CharField(max_length=50, null=True, verbose_name='PO ID')),
                ('supplier', models.CharField(max_length=50, null=True, verbose_name='Supplier')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.item', verbose_name='Item Stocked')),
            ],
            options={
                'verbose_name': 'Instock',
                'verbose_name_plural': 'Instocks',
            },
        ),
        migrations.RemoveField(
            model_name='outstock',
            name='size',
        ),
    ]
