# Generated by Django 4.2.30 on 2026-05-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_alter_instock_job_alter_outstock_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
