# Generated by Django 4.0.2 on 2022-05-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instock',
            name='size',
        ),
    ]
