# Generated by Django 4.2.30 on 2026-06-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_remove_item_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.customer', verbose_name='Customer'),
        ),
    ]
