# Generated by Django 4.0.2 on 2022-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_brand_alter_item_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='number_instock',
            new_name='instock_num',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='number_outstock',
            new_name='outstock_num',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('BAR', 'bar'), ('SHEET', 'sheet'), ('OTHER', 'other')], default='OTHER', max_length=50, verbose_name='Type of material'),
        ),
    ]
