# Generated by Django 4.0.2 on 2022-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_rename_number_instock_item_instock_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='instock_num',
        ),
        migrations.RemoveField(
            model_name='item',
            name='outstock_num',
        ),
        migrations.AddField(
            model_name='item',
            name='instock_number',
            field=models.IntegerField(default=0, verbose_name='Instock Number'),
        ),
        migrations.AddField(
            model_name='item',
            name='outstock_number',
            field=models.IntegerField(default=0, verbose_name='Outstock Number'),
        ),
    ]
