# Generated by Django 4.0.2 on 2022-06-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stockmanagement', '0011_searchsuggestion_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsuggestion',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='searchsuggestion',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
