# Generated by Django 4.0.6 on 2022-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0015_instock_quantity_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Quantity of Items Left Instock'),
            preserve_default=False,
        ),
    ]
