# Generated by Django 4.0.6 on 2022-08-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0017_alter_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instock',
            name='quantity_left',
        ),
    ]
