# Generated by Django 4.0.6 on 2022-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0020_alter_instock_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstock',
            name='instock',
        ),
    ]
