# Generated by Django 4.0.6 on 2022-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0022_remove_item_item_type_alter_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Max Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Min Price'),
        ),
    ]
