# Generated by Django 4.0.6 on 2023-08-26 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0024_alter_outstock_customer_alter_outstock_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked'),
        ),
    ]
