# Generated by Django 4.0.6 on 2026-01-06 08:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0025_alter_instock_price_alter_instock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.RemoveField(
            model_name='instock',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='outstock',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='outstock',
            name='job_id',
        ),
        migrations.AddField(
            model_name='instock',
            name='notes',
            field=models.CharField(max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='instock',
            name='store_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('accessory', 'Accessory'), ('machine', 'Machine'), ('service', 'Service')], default='metal', max_length=20, verbose_name='Store Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_quanity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Maximum Quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='min_quanity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Minimum Quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='notes',
            field=models.CharField(max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity of Item Stocked'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='store_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('accessory', 'Accessory'), ('machine', 'Machine'), ('service', 'Service')], default='metal', max_length=20, verbose_name='Store Type'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='invoice_id',
            field=models.CharField(default='UNDEFINED', max_length=50, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='instock',
            name='stock_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 6, 8, 48, 17, 691407, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Item SKU'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='stock_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 6, 8, 48, 38, 739619, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, verbose_name='Job ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.AddField(
            model_name='instock',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmanagement.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='outstock',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.job', verbose_name='Job'),
        ),
    ]
