# Generated by Django 4.0.6 on 2026-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0026_customer_remove_instock_job_id_remove_item_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Item SKU'),
        ),
    ]
