# Generated by Django 4.0.6 on 2026-01-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0027_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='max_quanity',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Maximum Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_quanity',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Minimum Quantity'),
        ),
    ]
