# Generated by Django 4.0.6 on 2026-01-13 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0028_alter_item_max_quanity_alter_item_min_quanity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='stock_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 8, 39, 37, 277895, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='stock_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 8, 39, 37, 277895, tzinfo=utc), verbose_name='Date'),
        ),
    ]
