# Generated by Django 4.0.6 on 2026-01-13 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0029_alter_instock_stock_date_alter_outstock_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='outstock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
